### ISSUE TITLE
The Keeper App(using React js)

### ISSUE THREAD

**Issue by nandinit02** [kokonior/Javascript-Projects#407]
This is a note taking app. @kokonior  Please assign me this task so that I can start working on it.
![Screenshot (230)](https://user-images.githubusercontent.com/58943594/194705370-5459f510-dbb9-4ec1-9fe1-ab4a4472dc06.png)

**Comment by kokonior** [comment]
Nggih

**Comment by kokonior** [comment]
Don't be too strict with the rules. The important thing is that you are accepted at hacktoberfest, that's enough. You have the freedom of uploading any file here.
